### ISSUE TITLE
Single-language bots are very impolite

### ISSUE THREAD

**Issue by nditada** [instedd/aida#123]
They don't greet you! :-)
![screen shot 2018-02-05 at 6 54 15 pm](https://user-images.githubusercontent.com/1359189/35830744-05b276f0-0aa6-11e8-8941-8083935f4c4f.png)

**Comment by nekron** [comment]
There is already a test that should be catching that error: https://github.com/instedd/aida/blob/master/test/aida/bot_test.exs#L85

**Comment by mmuller** [comment]
Still present in version 2496cdc

Preconditions:
* There is a Bot with the following skills:
* 1 Front Desk.
* 2 Keyword Responders (`KR1` and `KR2`).

Steps to reproduce:

* Send `Hi` to the bot.
* Remove the skill `KR1`.
* Publish the bot.
* Send `##RESET` to the bot.
* Send `Hi` to the bot.

Obtained result:
* The bot sends the `Didn't understand message`.

Screenshots:

![image](https://user-images.githubusercontent.com/518152/41929440-674a7356-794e-11e8-9743-b6949c0202ab.png)

![image](https://user-images.githubusercontent.com/518152/41929461-7ad7cb08-794e-11e8-8697-e007c73ecc0f.png)

**Comment by nekron** [comment]
This current behavior is probably related to #213 and it may have been caused by changes made to solve #148.

**Comment by mmuller** [comment]
Working properly in version 41093c5
