### ISSUE TITLE
Analytics don't work correctly

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#127]
All analytics are reset periodically (?) and as a consequence they do not reflect the right numbers  of users / messages received / messages sent.

**Comment by mmuller** [comment]
This issue can be reproduced in version 0.5.0 (ui)- 0.5.1 (engine)

**Comment by nditada** [comment]
solved, deployed and verified in staging.

**Comment by nditada** [comment]
@Lu-vam reports that there are still issues with this:

>  it looks like the count of active users is not yet right. From the screenshot below you can see that the app tells me that there were only 4 active users in the past month, however, from the Facebook page I can clearly count 7 from February 16:

![image001](https://user-images.githubusercontent.com/1359189/37423373-b3fc0ea2-27ce-11e8-8b83-156b9da071fb.jpg)
![image003](https://user-images.githubusercontent.com/1359189/37423375-b5832d32-27ce-11e8-98e0-68b23de2afc7.jpg)

**Comment by waj** [comment]
Please, keep in mind that when you select "this month", only active users since 1st of current month are considered (not the last 30 days).
