### ISSUE TITLE
Table KEY 

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#129]
Tables don't work when the 'KEY' is not a number: [ERROR: Could not find attribute named....]
![error table 1](https://user-images.githubusercontent.com/36440133/36969606-4979e816-2066-11e8-9a47-e5ff6b2a5416.PNG)
![error table 2](https://user-images.githubusercontent.com/36440133/36969607-499cbf44-2066-11e8-8b1c-46404933fc35.PNG)

**Comment by mmuller** [comment]
@Lu-vam The string `mariste` should be enclosed in quotes.
It should be something like: `In Mariste, WFP distribute food in {{ lookup('mariste', "test", "camp") }}`

**Comment by Lu-vam** [comment]
@mmuller thanks!
