### ISSUE TITLE
Not possible to invite collaborators on local instance of the bot 

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#130]
On our local instance of AIDA, it is not possible to invite collaborators to a bot: the invitation email is never sent out / received by the person wich is supposed to join the project. Thanks for looking into this!

**Comment by bcardiff** [comment]
@Lu-vam would you check again? It seems a setting was missing to setup the sender email address. It as using @instedd.org instead of @wfp.instedd.org and hence it was failing due to a domain issue.

**Comment by Lu-vam** [comment]
Hello @bcardiff ! The emails have been sent out now! Thanks for fixing this.

**Comment by bcardiff** [comment]
Great!

**Comment by Lu-vam** [comment]
Hi @bcardiff sorry I have to reopen this issue: while collaborators now receive the email invitation to collaborate to a bot, they are not able to accept the invitation. The bot doesn't appear on their bot list.
