### ISSUE TITLE
Skills introduction and clarification should not be mandatory

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#135]
At the moment to publish the bot it is necessary to fill in the skill introduction and clarification. As a consequence these show up at the beginning of a new conversation all together and this is annoying for the user. Skills introduction and clarification should not be mandatory.

**Comment by lorenzori** [comment]
there was a mistake in the issue description. The issue is that a skill shouldn't need "Skill explanation" or "Skill clarification" fields to be populated to be published.

**Comment by lorenzori** [comment]
https://github.com/0nkery sorry, our mistake.

**Comment by 0nkery** [comment]
@nekron, have you solved this issue? Because if not, I can handle it.

**Comment by nekron** [comment]
I'm actually not sure about the language_detector skill.

Should we allow it not to have an explanation message? Does it make any sense to have a bot that doesn't tell you anything if you haven't set up the proper language by "guessing" the right keyword?

Just to be clear, this skill will only be there if the bot has more than one language, if not, it will automatically use the only available language.

**Comment by lorenzori** [comment]
I think that allowing to not have explanation message for the language_detector gives more flexibility, but I think that yours is a good point. @Lu-vam any thoughts?
