### ISSUE TITLE
Handle survey and decision tree interruptions

### ISSUE THREAD

**Issue by nditada** [instedd/aida#147]
After other skill's conversation, surveys should not assume that a valid answer for a pending question is theirs.

But what to do? Are there situations where we DO want that to happen? Like

bot: what's your name?
user: why are you asking?
bot: because we need to know for this and that
user: nicolas
bot: thanks nicolas, how old are you?

**Comment by nekron** [comment]
Allow only one active skill at a time. Clear all other the active skills (surveys or decision trees) when launching a new one. This means, restart the survey if it's triggered again.

**Comment by nekron** [comment]
Related to #166 and #146

**Comment by mmuller** [comment]
Working properly in version 61d95e2
