### ISSUE TITLE
[RFC] Name and IDs per skill in manifest

### ISSUE THREAD

**Issue by nditada** [instedd/aida#15]
1- Skills will be renamed by users in the UI. 
2- Stats of Skill usage need to be persistent across renames.
3- Therefore we need an ID for a skill in the manifest.
4- We might also want to have the name of the skill in the manifest for logging purposes.
5- It might be good to not be strict about the type of the IDs to allow for manual creation or other tools to emit manifests. Maybe just a unique (not repeated in the manifest) string?

**Comment by bcardiff** [comment]
Having names will also be helpful for validating semantics of the manifest and report them back to the ui.
