### ISSUE TITLE
Store skill variables in "assets"

### ISSUE THREAD

**Issue by nekron** [instedd/aida#161]
- [ ] Create a new entity called Asset, in which a skill will store its generated data every time it's executed.

The asset will contain:
- session_id
- skill_id
- data (a flat key-value store)

A survey skill will have a different asset every time it runs.

- [ ] When querying for the value of that variable, look for it in the session first and then in all the assets. Mind to use only the latest instance of that value if more than one is present.

- [ ] Add an additional API route to get all the accumulated data. Allow filters for a given bot, skill, session, and date since and to.

- [ ] Answer with the latest asset data in the session data json and csv download, so this change doesn't breaks backwards compatibility with existing api's.

**Comment by mmuller** [comment]
Variables are working properly in version edbe7e1
