### ISSUE TITLE
Clarify better workings of confidence threshold

### ISSUE THREAD

**Issue by nditada** [instedd/aida#165]
@nditada please write something better

**Comment by nditada** [comment]
Not loving this...but it's the best I could come up with so far:
"Show when there is less than 20% confidence to tell two matching skills apart"

**Comment by nekron** [comment]
Fixed with https://github.com/instedd/aida-ui/commit/d4b02ee9989a7ad58fa05cfc652be4415a3d9898

**Comment by mmuller** [comment]
Text was replaced properly in version 56c0b32
