### ISSUE TITLE
Adjust top bar style

### ISSUE THREAD

**Issue by jkicillof** [instedd/aida#180]
- [ ] Remove tabs zone when is empty
- [ ] Vertically align FAB icon
- [ ] Change font-size to 14px
- [ ] Change main navigation height to 48px
- [ ] The area below the main navigation should be 108px height
- [ ] The text next to the Aida icon should have a font-size of 20px
- [ ] Tabs area should be 48px height

**Comment by mmuller** [comment]
Working properly in version 420e3a5
