### ISSUE TITLE
Adjust collaborators section style

### ISSUE THREAD

**Issue by jkicillof** [instedd/aida#194]
- [x] Checks for active collaborators should be black, not blue
- [x] The table should have a minimum of 5 rows even if they are less collaborators
- [x] Show remove icon only on row hover

https://projects.invisionapp.com/d/main#/console/12115078/299944180/preview
The data table style adjustments are on issue #179

**Comment by mmuller** [comment]
Working properly in version 23e93ec
Remove icon is always displayed, the tooltip with the message `Remove collaborator` is displayed on row hover.
