### ISSUE TITLE
Adjust relevance component

### ISSUE THREAD

**Issue by jkicillof** [instedd/aida#200]
- [ ] Relevance icon should have 24px font-size
- [ ] On blank state the border shouldn't be dashed
- [ ] 'RELEVANCE' string should be always visible
- [ ] Input baseline should online be visible on focus
- [ ] Relevance hint should be italic
- [ ] Relevance hint font-color should be #cccccc
- [ ] Content is vertically misaligned

Relevance blank
https://projects.invisionapp.com/d/main#/console/12115078/299944201/preview

Relevance
https://projects.invisionapp.com/d/main#/console/12115078/299944211/preview

**Comment by mmuller** [comment]
Working properly in version 56c0b32
