### ISSUE TITLE
Adjust invite confirmation style

### ISSUE THREAD

**Issue by jkicillof** [instedd/aida#205]
- [ ] Remove bullets, showing the roles separated by comma
- [ ] Change the button color to blue
- [ ] Reduce the icon font-size
- [ ] Use the admin name instead of the email

https://projects.invisionapp.com/d/main#/console/12115078/299944179/preview

**Comment by nekron** [comment]
If admin name is not present, default to email.

**Comment by mmuller** [comment]
Working properly in version a32a18f
