### ISSUE TITLE
[ui] De-hardcode bot index

### ISSUE THREAD

**Issue by nekron** [instedd/aida#217]
Bot index values are always blank and the type is always Facebook.

Populate the table with the right values.

For channel types, display a list of the types, comma separated.

For uses and Last activity, use the values from analytics screen.

https://projects.invisionapp.com/d/main#/console/12115078/299944224/preview

**Comment by vtiffenberg** [comment]
Started in branch feature/217-dehardcode-bot-index 
Putting it back in ready.

**Comment by mmuller** [comment]
Working properly in version b47a13d
