### ISSUE TITLE
Scheduled messages with errors are not highlighted in the sidebar

### ISSUE THREAD

**Issue by mmuller** [instedd/aida#245]
UI Version 460d9bb
Engine Version edbe7e1

![image](https://user-images.githubusercontent.com/518152/43533438-2bfb2882-958b-11e8-8e1d-9df9463f5505.png)

**Comment by nekron** [comment]
Actually they are. The problem is that the dots are being hidden behind the ellipsis

**Comment by mmuller** [comment]
Working properly in version 5c011b2
