### ISSUE TITLE
Add wit.ai setup to the manifest

### ISSUE THREAD

**Issue by nekron** [instedd/aida#247]
Parse wit.ai credentials and skill setup.

- Include in every skill with keywords the possibility of not having those keywords and instead having a list of training sentences. Indexed by language, but with only english being supported for now.
```
"training_sentences" : {
  "en": ["I need some menu information", "What food do you serve?"]
}
```

- In the general bot setup include a natural language interface setup, with a provider and a token. The provider being only `wit_ai` for now.
```
"natural_language_interface" : {
  "provider" : "wit_ai",
  "auth_token" : "ASDHDEAWREARTDJFHZDGSFEDFGAFD"
}
```

- Parse both fields and ensure that if any skill provides a list of training sentences, the `natural_language_interface` is properly setup.

- Check those credentials against wit.ai when parsing the bot to ensure they are valid.

**Comment by mmuller** [comment]
Working properly in version b47a13d
