### ISSUE TITLE
[UI] Allow to select a row in the human override schedule 

### ISSUE THREAD

**Issue by mmuller** [instedd/aida#250]
Toggle the entire row/column when clicking on the label.

Add a blank clickable gap for the hours that aren't present.

If at least one hour is off, toggle the entire row/column on. If they are all on, toggle all off.

**Don't** alternate the state of each bucket independently to give an exact negative of what the user has selected.

The idea is to help the user toggle an initial time window.

![image](https://user-images.githubusercontent.com/518152/43645430-3edb2d7a-9708-11e8-925e-4b18b3004f82.png)

**Comment by nekron** [comment]
Closing in favor of https://github.com/instedd/aida/issues/254
