### ISSUE TITLE
JS warning in surveys

### ISSUE THREAD

**Issue by nekron** [instedd/aida#266]
Survey's date picker field is throwing a react warning.

```warning.js?6327:33 Warning: Failed prop type: Invalid prop `leftIcon` of type `boolean` supplied to `TextField`, expected a single ReactElement.
    in TextField (created by DatePickerContainer)
    in DatePickerContainer (created by Survey)
    in div (created by Survey)
    in div (created by Survey)
    in Survey (created by Connect(Survey))
    in Connect(Survey) (created by SkillComponent)
    in SkillComponent (created by BotSkill)
    in BotSkill (created by Connect(BotSkill))
    in Connect(BotSkill) (created by Route)
    in Route (created by BotBehaviourComponent)
    in div (created by Paper)
    in Paper (created by MainWhite)
    in div (created by MainWhite)
    in aux (created by MainWhite)
    in MainWhite (created by BotBehaviourComponent)
    in BotBehaviourComponent (created by Connect(BotBehaviourComponent))
    in Connect(BotBehaviourComponent) (created by Route)
    in Route (created by BotLayoutComponent)
    in main (created by Layout)
    in div (created by Layout)
    in Layout (created by AppLayout)
    in AppLayout (created by Connect(AppLayout))
    in Connect(AppLayout) (created by BotLayoutComponent)
    in BotLayoutComponent (created by Connect(BotLayoutComponent))
    in Connect(BotLayoutComponent) (created by Route)
    in Route (created by withRouter(Connect(BotLayoutComponent)))
    in withRouter(Connect(BotLayoutComponent)) (created by Route)
    in Route (created by App)
    in div (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in Provider (created by App)
    in App```

**Comment by mmuller** [comment]
Working properly in version f94971c
