### ISSUE TITLE
Mobile friendly chat

### ISSUE THREAD

**Issue by nekron** [instedd/aida#268]
Create stand alone web page without login that exposes a mobile friendly chat.
It will connect using the websocket protocol to the already exposed path in the runtime.

As a bonus, time-box the possibility of having a separated javascript build for the client, without react and redux, with the goal of lightening the client and make it easier to use in a slow connection environment.

**Comment by mmuller** [comment]
It is not possible to use the chat on a mobile phone. When focusing the text field the keyboard is not displayed.

**Comment by mmuller** [comment]
Working properly in version 71621e5
