### ISSUE TITLE
Unexpected behavior when deleting a skill connected to wit.ai

### ISSUE THREAD

**Issue by mmuller** [instedd/aida#269]
Version f94971c

Preconditions:

- There is a Keyword Responder `KR` connected to wit.ai.
- The valid keyword for `KR` is `VK`.

Steps to reproduce:

1. Navigate to the Skills listing.
2. Remove `KR`.
3. Send `VK` to the bot.

Obtained:

- The Bot doesn't reply.
- The following error is logged: https://sentry.io/instedd/aida-staging/issues/682977409/?environment=prod

Expected:

- The Bot should send the `Didn't understand message`.

**Comment by nekron** [comment]
```(Protocol.UndefinedError) protocol Aida.Skill not implemented for nil.```

For some reason wit is still answering with the deleted skill's id.

**Comment by mmuller** [comment]
http://recordit.co/Y4UerNlRy2
