### ISSUE TITLE
Refactor of Sessions Table

### ISSUE THREAD

**Issue by waj** [instedd/aida#28]
Sessions must be scoped by bot. Let's include the bot_id inside the session and the sessions table.

**Comment by lmatayoshi** [comment]
- [ ] Add `bot_id`, `bot_provider` and `provider_key` to `Sessions` table
- [ ] Move information in current `id` to the previously added columns: `bot_id`, `bot_provider` and `provider_key`
- [ ] Copy `UUID` values to `id`
- [ ] Remove `UUID` column 
- [ ] Update `id` `column_type` from `string` to `binary_id`

**Comment by lmatayoshi** [comment]
@mmuller, you don't have to verify this issue because it is a refactor. It was solved properly if everything is still working :ok.
