### ISSUE TITLE
Given a Bot Id, how can I get programmatically the access token for the Websocket Channel?

### ISSUE THREAD

**Issue by zontarian** [instedd/aida#285]
Hello
we are planning to give our users the ability to choose among all the bots published on a given endpoint.

Having created an API Token in the API page, we can query our bots with
`https://aida-stg.instedd.org/api/v1/bots.json?access_token=<API_KEY>`

Then from the JSON we can detect:
* the bot ID (number)
* the bot UUID (16 byte hex string)
* the bot name.

What we are missing now is the access key we have set up in the `Channel/websocket` page, and that is needed when setting up and subscribing to the Phoenix websocket channel.
We can of course decide that the token is always a given string, and as a guideline, tell our bot creators to always set up the access key on the `websocket` page to always use the same string.

But an automated solution would be preferable I think. Or maybe we are missing the point, and doing things in the wrong way? Is there another way to retrieve it?

Thanks

**Comment by nditada** [comment]
Hi @zontarian, there is no programmatic way to get channel tokens. I think for now you'll have to instruct users to get it from the page.

**Comment by zontarian** [comment]
Ok, for the moment we will hard wire it in the code.
Thanks
