### ISSUE TITLE
Endpoints to list sessions and get session logs

### ISSUE THREAD

**Issue by waj** [instedd/aida#47]
Add the following endpoints to the SessionController:

### Session index
`GET /api/bots/<bot_id>/sessions`

This endpoint should return the existing sessions for the bot:
```json
{
  "data": [
    {"id": "", "first_message": "2017-01-01T01:23:45Z", "last_message": "2017-01-01T01:23:45Z"}
  ]
}
```

### Session log
`GET /api/bots/<bot_id>/sessions/<session_id>/log`

```json
{
  "data": [
    {"timestamp": "", "direction": "incoming | outgoing", "content": ""}
  ]
}
```

**Comment by mmuller** [comment]
Working properly in version aa7d8ec
