### ISSUE TITLE
Support pictures content from respondents

### ISSUE THREAD

**Issue by waj** [instedd/aida#50]
Currently, only text is supported as content. Let's add support for pictures.

  - [x] Change `Message.content` so it's either a `TextContent` or a `ImageContent`. The `ImageContent` will contain the URL received by the channel
  - [x] Fix all the skills expecting text from the content (most of the time, skills will return a `confidence = 0` when the content is an image)
  - [x] Support `image` questions in the survey. When the question is executed, download and store the image sent by the user in a new `images ` table. Store the URL to retrieve the image in the session value.

**Comment by bcardiff** [comment]
Some ideas/doubts on this feature:

1. It would be great to know the url / prefix the pictures will be uploaded so we map that upon deployment.
2. It might be good to have a public_url environment setting in the backed so the ui does not need to rewrite the url inside json.
3. Is there plan to support upload of images for the websocket channel?
