### ISSUE TITLE
Bot with survey fails with preview and publish

### ISSUE THREAD

**Issue by nditada** [instedd/aida#68]
A minimal bot with frontdesk messages and the attached survey fails with a "unable to join preview channel".

[Chatbot 18 survey.xls.zip](https://github.com/instedd/aida/files/1632814/Chatbot.18.survey.xls.zip)

**Comment by waj** [comment]
This is because we're supporting only lowercase identifiers:
https://github.com/instedd/aida/blob/master/lib/aida/expr/expr_lexer.xrl#L5

**Comment by waj** [comment]
I added two tasks (#70 and #71) that should handle different facets of this problem

**Comment by mmuller** [comment]
Working properly in version aa7d8ec
