### ISSUE TITLE
Reorder skills

### ISSUE THREAD

**Issue by luciaVAM** [instedd/aida#76]
It should be possible to reorder the skills - this is particularly important as they are presented in the same order in which they appear in the platform. If the user forgets to create a skill, she needs to delete all the preceding ones to include the new skill. Being able to duplicate skills within the same chatbot project would be also very useful.

**Comment by nditada** [comment]
Yes, agreed, but out of scope for now, let's keep it in the backlog for the next round.

**Comment by lmatayoshi** [comment]
A new issue was opened in order to add this feature: https://github.com/instedd/aida-ui/issues/137
