### ISSUE TITLE
Preview channel not working 

### ISSUE THREAD

**Issue by luciaVAM** [instedd/aida#79]
As shown in the picture, the preview channel is not working (I tried to attach also the manifest but the platform said the type of file is not supported).

![aida error](https://user-images.githubusercontent.com/18008195/35148212-adce16e8-fd11-11e7-88cb-940bb60a237f.PNG)

**Comment by nditada** [comment]
@luciaVAM Can you zip the manifest and upload it here?

**Comment by mmuller** [comment]
[manifest-18-2018-01-22t08_16_27z.zip](https://github.com/instedd/aida/files/1653501/manifest-18-2018-01-22t08_16_27z.zip)

**Comment by nditada** [comment]
@luciaVAM if you add quotes to rome, like this: ${location}='Rome' and try again, it should work.
